### ISSUE TITLE
Able to mount non-vanilla sword as bayonette

### ISSUE THREAD

**Issue by WimpieRatte** [AlanorMiga/Just-Enough-Guns#13]
Just Enough Guns 0.4.0
Minecraft 1.20.1

Mounting the Enderium Sword, from Majrusz's Progressive Difficulty mod, looks funny, because the attachment still works, but visually looks like the sword is stuck to the gun in a strange way.

Your changelog for 0.4.0 mentioned "Vanilla swords can now be attached", so I'm surprised that I can attach a non-vanilla sword at all?

Also, when charging with a bayonette, I don't damage entities that I run into.
Or should I press the melee (v) button during my charge? (I expected the charge to damage entities automatically)

**Comment by MigaMiDev** [comment]
Well yeah, I specifically programmed it so you could ATTACH modded items registered as "SwordItem". But I still haven't found a way to make them render properly, since they all use different custom models.

The charge does damage entities naturally without the need for further input. You need to sprint for 2 seconds before the charging is activated. You'll know when it activates because you also receive  speed boost.

**Comment by WimpieRatte** [comment]
aaah. Thank you! I only tried it for short distances.
Cool update, btw.

**Comment by MigaMiDev** [comment]
Thank you!
