### ISSUE TITLE
[Suggestion] Alternative fire

### ISSUE THREAD

**Issue by neirenoir** [AlanorMiga/Just-Enough-Guns#21]
Hi there! I am working on a Perfect Dark/GoldenEye themed modpack, and I think JEG would be the most fitting gun mod for them. Thing is, Perfect Dark's main gimmick is having an alternative fire mode for each gun, but nor JEG nor no other gun mod I know of support this feature. Alternative fire could be a useful feature as well for grenade launcher or shotgun attachments for weapons.

Would it be too much to ask for...?
1. A new keybind for alternative fire (or toggling fire mode, as you see fit)
2. A method for guns that is invoked whenever a player attempts to alt fire their weapon

In addition, do you have any resources on how to add our own guns? I tried searching for Mr. Crayfish Gun guides and I found nothing on the Internet. I could try combing through the code and work backwards from there, but if you have any resource on the matter, it would be of great help.

Thanks!

**Comment by MigaMiDev** [comment]
I endorse suggestions via the JEG's discord server!

It's not that it's too much to ask for, it's just that there are more important things to adress first, mainly the bugs, then keep up with the content and gun progression. Currently I am working on new crafting and gun obtainment systems, so not soon.

And about the resources, I would totally suggest you to look up Mo' Than Enough Guns, is an add-on for JEG, but it's open source and it provides the code to add Guns, Ammo, Workbenches (system has been improved this non-released version). 

Going back at the alternate fire mechanic, it's just that I want to make every gun feel unique or serve a different purpose according to the scenario (wherever possible). Mainly I try to avoid copying and pasting guns. I want the mod to feel unique and alive, and making it so almost every gun could adapt to every scenario goes agaisnt that reasoning. I have however given thought to adding attachments with secondary fire, because it is an idea I do like and would definetly think of implementing it in the future!

**Comment by neirenoir** [comment]
I didn't know about the Discord. Sorry! I will join as soon as I am home. We can close the issue here, then.

>Going back at the alternate fire mechanic, it's just that I want to make every gun feel unique or serve a different purpose according to the scenario (wherever possible).

I totally understand that. I think my favourite weapon in the mod is the bolt action rifle, although I have not tried them all yet. It feels oomph-y.

That said, secondary fire modes in Perfect Dark were pretty tame save for a few exceptions. Pistols got a melee attack, many weapons got ammo dump, some got radars, and some got absolutely crazy, like planting down the weapon into a landmine. I feel like letting the gun object (with the attachments and all that) handle what to do after a toggle would be the sanest and most flexible way of implementing this.

As I said, I will get into the Discord ASAP. If you can help me locate where some stuff is inside the codebase, I can try to code the alt fire framework and submit a PR so addons can make use of it.

**Comment by neirenoir** [comment]
Closed for now as it has been posted in the Discord.
