### ISSUE TITLE
Games crashes when joining friend's server

### ISSUE THREAD

**Issue by Acenthus** [AlanorMiga/Just-Enough-Guns#9]
Title basically says it all, the server was done through essential if that's important to know as well. [Crash Log](https://pastebin.com/raw/NSzFC4ur)
I'd be willing to provide the full log if you have somewhere private I could send it as it has my IP information which I'd rather not give to the public for obvious reasons lol.

**Comment by MigaMiDev** [comment]
Thanks for letting me know!
The log prints out a stacktrace referring to the GunRenderingHandler class, which I don't remember modifying.
I will keep looking into this, however, try to both of you run freshly downloaded (configured) copies of JEG, and see if the issue resolves.

Without further context is hard to say what could have caused it, since this is the first time this issue pops up.
Thanks again for letting me know!

**Comment by Acenthus** [comment]
Should probably mention that looking into the error I found like 2 results of people having a near identical issue with MrCrayFish's gun mod so I'd guess it's an incompatibility or forge issue. The other posts said nothing about how to fix the issue (if they ever did) so I'll probably let you know if I can figure out the mod that's breaking it.

**Comment by Acenthus** [comment]
So I'm guessing it was essential somehow that broke it because using e4mc to connect instead made it work suddenly, so problem solved I guess?
